Repository luisewinzer/SE-Projekt, pull requests merged in 2024-07, with the labels that each got.

#11 8 bugfix l r screen
  L-R-Screen/L-R-Screen/Database.cs
  L-R-Screen/L-R-Screen/DeceasedPerson.cs
  L-R-Screen/L-R-Screen/L-R-Screen.csproj
  L-R-Screen/L-R-Screen/Login.cs
  L-R-Screen/L-R-Screen/Program.cs
  L-R-Screen/L-R-Screen/Registration.cs
  L-R-Screen/L-R-Screen/Resources/db_users.mdb
  L-R-Screen/L-R-Screen/db_users.mdb
Labels: bug

#12 Enhancements L-R-Screen
  L-R-Screen/L-R-Screen/Login.cs
  L-R-Screen/L-R-Screen/Registration.cs
  L-R-Screen/L-R-Screen/db_users.mdb
Labels: enhancement

#13 Design MainPage
  L-R-Screen/L-R-Screen/L-R-Screen.csproj
  L-R-Screen/L-R-Screen/MainPage.Designer.cs
  L-R-Screen/L-R-Screen/MainPage.cs
  L-R-Screen/L-R-Screen/Properties/Resources.Designer.cs
  L-R-Screen/L-R-Screen/Properties/Resources.resx
  L-R-Screen/L-R-Screen/Resources/Tombstone.png
Labels: design

#45 Update UML-Diagramm
  Klassendiagramm.plantuml
  UML-Diagramm.plantuml
Labels: update

#47 Added Exit, Improved Date Logik
  CoffinChronicles/L-R-Screen/DataRequest.cs
  CoffinChronicles/L-R-Screen/Login.Designer.cs
  CoffinChronicles/L-R-Screen/Login.cs
  CoffinChronicles/L-R-Screen/Registration.Designer.cs
  CoffinChronicles/L-R-Screen/Registration.cs
  CoffinChronicles/L-R-Screen/bin/Debug/DatabaseCC.mdb
  CoffinChronicles/L-R-Screen/bin/Debug/L-R-Screen.exe
  CoffinChronicles/L-R-Screen/bin/Debug/L-R-Screen.pdb
  CoffinChronicles/L-R-Screen/obj/Debug/CoffinChronicles.csproj.FileListAbsolute.txt
  CoffinChronicles/L-R-Screen/obj/Debug/CoffinChronicles.csproj.GenerateResource.cache
  CoffinChronicles/L-R-Screen/obj/Debug/DesignTimeResolveAssemblyReferencesInput.cache
  CoffinChronicles/L-R-Screen/obj/Debug/L-R-Screen.exe
  CoffinChronicles/L-R-Screen/obj/Debug/L-R-Screen.pdb
Labels: bug

#51 Readme überarbeitet
  README.md
Labels: documentation

#52 Access Tabelle zurücksetzen
  CoffinChronicles/L-R-Screen/bin/Debug/DatabaseCC.mdb
Labels: update
